-- F.6.1 — brain_runs + brain_decisions tables (Brain orchestrator memory persistence)
-- Cross-ref: .claude/PLAN.md § F.6 Decisões Cristalizadas D4 (per-run cadence) + D7 (replay)
-- D4: each Brain.decide() invocation persists 1 row brain_runs + N rows brain_decisions per state transition.
-- D7: replay CLI/API only — UI tab F.future (F.8 cost observability cross-ref).
-- F.6.1 só CREATE tables (vazias) — F.6.3 implementa persistence write-path real.
-- Apply VM: sqlite3 ~/.hermes/data/command_center.db < migrations/2026_06_brain_runs_decisions.sql
-- Apply PC: sqlite3 hermes_local.db < migrations/2026_06_brain_runs_decisions.sql

-- 1) brain_runs — 1 row per Brain.decide() invocation.
CREATE TABLE IF NOT EXISTS brain_runs (
    id                  TEXT PRIMARY KEY,                  -- uuid4 generated by Brain.decide()
    intent              TEXT NOT NULL,                     -- INTENT_REGISTRY key (6 entries F.6.1)
    context_json        TEXT,                              -- JSON dump of input context
    started_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    finished_at         TIMESTAMP,                         -- NULL while running
    final_state         TEXT,                              -- 'completed' | 'requires_confirm' | 'error' | 'aborted'
    final_result        TEXT,                              -- JSON dump of result payload
    total_latency_ms    INTEGER,
    total_cost_credits  REAL DEFAULT 0.0,                  -- F.6.1 always 0.0 (no LLM call); F.6.2 tracks real
    confidence_score    REAL,
    requester           TEXT,                              -- 'owner_dashboard' | 'daemon' | 'api' | 'cron'
    otel_trace_id       TEXT                               -- F.6 HARD REQ: cross-ref mcp_calls.context_id+turn_idx
);

CREATE INDEX IF NOT EXISTS idx_brain_runs_intent      ON brain_runs(intent, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_brain_runs_state       ON brain_runs(final_state);
CREATE INDEX IF NOT EXISTS idx_brain_runs_started     ON brain_runs(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_brain_runs_otel        ON brain_runs(otel_trace_id);

-- 2) brain_decisions — N rows per Brain.decide() — one per state transition.
CREATE TABLE IF NOT EXISTS brain_decisions (
    id                  TEXT PRIMARY KEY,                  -- uuid4 per transition
    run_id              TEXT NOT NULL REFERENCES brain_runs(id) ON DELETE CASCADE,
    sequence            INTEGER NOT NULL,                  -- order within the run (1..N)
    state_from          TEXT NOT NULL,                     -- BrainState value
    state_to            TEXT NOT NULL,                     -- BrainState value
    tool_invoked        TEXT,                              -- 'mcp.hermes-llm.route' | 'mcp.hermes-prospects.score_lead' | ...
    tool_args_json      TEXT,                              -- JSON dump (sanitize sensitive keys per hermes-llm pattern)
    tool_result_json    TEXT,                              -- JSON dump (truncated if >32KB)
    rationale           TEXT,                              -- short reasoning summary captured from LLM call (F.6.2)
    latency_ms          INTEGER,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_brain_decisions_run        ON brain_decisions(run_id, sequence);
CREATE INDEX IF NOT EXISTS idx_brain_decisions_tool       ON brain_decisions(tool_invoked);
CREATE INDEX IF NOT EXISTS idx_brain_decisions_created_at ON brain_decisions(created_at DESC);
