"""F.4.2 — Auto-Skill Loop orchestrator (lab sandbox + GitHub MCP PR + Workflow trigger).

Sub-commits:
  C1 (this commit) — dispatch_sandbox_test (D1 PIVOT inline YAML validation)
  C2 (next)        — dispatch_github_pr (D2/D3/D4/D5 GitHub MCP PR creation)
  C3 (last)        — trigger_workflow_synthesis (D6 manual API trigger)

PIVOT D1 — Lab sandbox = inline YAML validation + mock (NOT REUSE
mcp.hermes-skills.test_skill_dryrun direct). Reason: F.5.2
test_skill_dryrun(skill_name, input_data, mock_llm=True) reads YAML from disk
(skills/*.yaml), does NOT accept yaml_blob param. Proposal YAML is staging-only
(skill_proposals.yaml_blob), not yet in skills/. Inline validation is an honest
match of F.5.2 mock_llm=True scaffold semantics (both return stub responses).

PIVOT D7 — Cost tracking via mcp_calls.requester='brain-f4' (NOT extra schema
column). Reason: F.5.3 mcp_calls schema 9 cols original (id, server, tool, args,
response, error, duration_ms, requester, created_at). Aggregate cost via
`WHERE requester LIKE 'brain-%'`.

F.future backlogs:
  - F.5.2 enhance test_skill_dryrun to accept yaml_blob param → refactor here.
  - Migration extra column quando F.8/F.future precisar nova dimensão.

Cross-ref:
  .claude/PLAN.md § "F.4.2 Decisões Cristalizadas" (commit 4f09f52)
    + PIVOT D1/D7 owner alignment (commit b8fe9d2)
  api/skills.py F.4.1 stubs labeled → substituídos C1/C2/C3
  core/skill_proposals.py F.4.1 update_lab_result + update_pr_status (wired)
  brain/dispatch.py F.6.2 GatewayDispatcher (consumir mcp.* via gateway)
"""
from __future__ import annotations

import asyncio
import difflib
import json
import logging
import os
import re
import sqlite3
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

import yaml

from brain.dispatch import GatewayDispatcher
from core.skill_proposals import (
    SkillProposalsManager,
    _connect as _sp_connect,
    ensure_synthesis_runs_table,
    manager as proposals_manager,
)

log = logging.getLogger("hermes.auto_skill_runner")

# R5-PHASE2 — per-role bearer for F.4 AutoSkillRunner (falls back to shared bearer)
_F4_BEARER: str = os.getenv("HERMES_GATEWAY_BEARER_BRAIN_F4") or os.getenv("HERMES_GATEWAY_OAUTH_SECRET", "")

# D1 PIVOT — minimum YAML keys required to be considered a valid skill proposal.
_REQUIRED_YAML_KEYS: tuple[str, ...] = ("name", "version")

# At least ONE of these required (LLM-driven skill OR declarative pipeline).
_REQUIRE_EITHER: tuple[str, ...] = ("provider", "steps")

# D1 — lab sandbox timeout cap (defensive; inline validation is microseconds).
LAB_TIMEOUT_SECONDS: float = 60.0

# D7 PIVOT — requester encodes chapter context in mcp_calls (no schema change).
F4_REQUESTER: str = "brain-f4"

# C2 GitHub MCP defaults (override via env). Repo derived from origin.
_DEFAULT_GITHUB_OWNER: str = "caiolea0"
_DEFAULT_GITHUB_REPO: str = "hermes-cloud-studio"
_DEFAULT_GITHUB_BASE: str = "master"

# C2 PR body truncation caps (PR conversation hygiene).
_LAB_STREAM_TRUNCATE: int = 2000
_YAML_DIFF_TRUNCATE: int = 5000

# C2 PR body auto-template (D2).
PR_BODY_TEMPLATE: str = """## Skill Proposal: {name}

**Source pattern**: {source_pattern}
**Proposal ID**: `{proposal_id}`

### YAML diff (vs existing skills/)

```diff
{yaml_diff}
```

### Lab test result

- **Status**: {lab_test_status}
- **Latency**: {latency_ms}ms
- **Exit code**: {exit_code}
- **stdout**: ```{stdout_truncated}```
- **stderr**: ```{stderr_truncated}```

### Brain rationale

{synthesis_rationale}

---
🤖 Auto-generated by Hermes F.4 Auto-Skill Loop · `mcp.github.create_pull_request` · requester=`brain-f4`
"""


def _slugify(name: str, max_len: int = 40) -> str:
    """D3 — lowercase-dashed slug max 40 chars (trailing dash stripped)."""
    slug = re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")
    truncated = slug[:max_len].rstrip("-")
    return truncated or "unnamed"


def _shortid(proposal_id: str) -> str:
    """D3 — first 6 chars of proposal_id (UUID first segment)."""
    head = (proposal_id or "").split("-")[0]
    return head[:6] or "000000"


class AutoSkillRunner:
    """F.4.2 orchestrator: lab sandbox dispatch + GitHub MCP PR + Workflow trigger.

    C1 implements only dispatch_sandbox_test + helpers (D1/D3/D7 PIVOTs).
    C2 will add dispatch_github_pr; C3 will add trigger_workflow_synthesis.
    """

    def __init__(
        self,
        dispatcher: Optional[GatewayDispatcher] = None,
        manager: Optional[SkillProposalsManager] = None,
    ) -> None:
        self.dispatcher = dispatcher or GatewayDispatcher(bearer=_F4_BEARER)
        self.manager = manager or proposals_manager

    # ------------------------------------------------------------------
    # D1 PIVOT — inline YAML validation (lab sandbox mock)
    # ------------------------------------------------------------------

    def _validate_yaml_inline(self, yaml_blob: str) -> dict[str, Any]:
        """Parse + validate proposed skill YAML inline.

        Returns lab_test_result dict matching the schema persisted in
        skill_proposals.lab_test_result:

            {status, stdout, stderr, latency_ms, exit_code, mock}

        D1 honest match of F.5.2 mock_llm=True scaffold semantics.
        """
        start = time.perf_counter()
        stdout_lines: list[str] = []
        stderr_lines: list[str] = []
        status = "passed"
        exit_code = 0
        parsed: Any = None

        # Parse
        try:
            parsed = yaml.safe_load(yaml_blob)
        except yaml.YAMLError as exc:
            stderr_lines.append(f"yaml.YAMLError: {exc}")
            status = "failed"
            exit_code = 1

        # Structure check
        if status == "passed" and not isinstance(parsed, dict):
            stderr_lines.append("YAML root must be a mapping (dict)")
            status = "failed"
            exit_code = 1

        # Required keys present
        if status == "passed":
            missing = [k for k in _REQUIRED_YAML_KEYS if k not in parsed]
            if missing:
                stderr_lines.append(f"Missing required key(s): {missing}")
                status = "failed"
                exit_code = 1

        # At least one of provider | steps
        if status == "passed":
            if not any(k in parsed for k in _REQUIRE_EITHER):
                stderr_lines.append(
                    f"At least one of {list(_REQUIRE_EITHER)} required"
                )
                status = "failed"
                exit_code = 1

        if status == "passed":
            present = sorted(
                k for k in parsed
                if k in (_REQUIRED_YAML_KEYS + _REQUIRE_EITHER)
            )
            stdout_lines.append(f"Validation OK: keys {present}")

        latency_ms = int((time.perf_counter() - start) * 1000)
        return {
            "status": status,
            "stdout": "\n".join(stdout_lines),
            "stderr": "\n".join(stderr_lines),
            "latency_ms": latency_ms,
            "exit_code": exit_code,
            "mock": True,
        }

    # ------------------------------------------------------------------
    # dispatch_sandbox_test — fetch proposal → validate → persist
    # ------------------------------------------------------------------

    async def dispatch_sandbox_test(self, proposal_id: str) -> dict[str, Any]:
        """C1 — orchestrate lab validation for a single proposal.

        Transitions proposal.status: lab_running → lab_passed | lab_failed.
        Persists lab_test_result via manager.update_lab_result.

        Returns:
            {ok, proposal_id, lab_test_result, new_status}

        Raises:
            LookupError when proposal_id missing (api layer maps to 404).
        """
        proposal = self.manager.get(proposal_id)  # raises LookupError

        try:
            await asyncio.wait_for(
                self._run_validation(proposal),
                timeout=LAB_TIMEOUT_SECONDS,
            )
        except asyncio.TimeoutError:
            lab_result = {
                "status": "failed",
                "stdout": "",
                "stderr": f"lab timeout after {LAB_TIMEOUT_SECONDS}s",
                "latency_ms": int(LAB_TIMEOUT_SECONDS * 1000),
                "exit_code": 124,
                "mock": True,
            }
            self.manager.update_lab_result(
                proposal_id, lab_result, lab_test_status="failed",
            )
            log.warning(
                "lab dispatch timeout proposal_id=%s requester=%s",
                proposal_id, F4_REQUESTER,
            )
            await self._ws_emit("brain.skill_lab_validated", {
                "proposal_id": proposal_id,
                "status": "failed",
                "reason": "timeout",
            })
            return {
                "ok": False,
                "proposal_id": proposal_id,
                "lab_test_result": lab_result,
                "new_status": "lab_failed",
            }

        updated = self.manager.get(proposal_id)
        lab_result = json.loads(updated.get("lab_test_result") or "{}")
        new_status = updated.get("status")

        await self._ws_emit("brain.skill_lab_validated", {
            "proposal_id": proposal_id,
            "status": lab_result.get("status"),
            "latency_ms": lab_result.get("latency_ms"),
        })

        log.info(
            "lab dispatch proposal_id=%s requester=%s status=%s latency=%sms",
            proposal_id, F4_REQUESTER, lab_result.get("status"),
            lab_result.get("latency_ms"),
        )
        return {
            "ok": lab_result.get("status") == "passed",
            "proposal_id": proposal_id,
            "lab_test_result": lab_result,
            "new_status": new_status,
        }

    async def _run_validation(self, proposal: dict[str, Any]) -> None:
        """H2 FORWARD — try subprocess real via gateway, fallback to inline.

        Gateway path: invoke_tool(server='hermes-skills', tool='test_skill_dryrun',
        args={'yaml_blob': ..., 'timeout_seconds': 60}) → subprocess isolated.
        Fallback: _validate_yaml_inline (PIVOT D1 original, mock=True).
        """
        yaml_blob = proposal.get("yaml_blob") or ""
        lab_result: dict[str, Any] | None = None

        # H2: Try gateway dispatch test_skill_dryrun with yaml_blob.
        try:
            gw_response = await self.dispatcher.invoke_tool(
                server="hermes-skills",
                tool="test_skill_dryrun",
                args={
                    "yaml_blob": yaml_blob,
                    "input_data": {},
                    "timeout_seconds": 60,
                },
                requester=F4_REQUESTER,
                caller_chapter="F.4",
            )
            candidate = (
                gw_response.get("response", {})
                if isinstance(gw_response, dict)
                else {}
            )
            if isinstance(candidate, dict) and "status" in candidate:
                lab_result = candidate
            else:
                log.debug(
                    "H2 gateway response missing status field: %s",
                    gw_response.get("error") if isinstance(gw_response, dict) else gw_response,
                )
        except Exception as exc:
            log.warning(
                "H2 _run_validation gateway exception, fallback inline: proposal_id=%s err=%s",
                proposal.get("id"),
                exc,
            )

        # Fallback: inline validation (PIVOT D1 original logic preserved).
        if lab_result is None:
            lab_result = self._validate_yaml_inline(yaml_blob)

        self.manager.update_lab_result(
            proposal["id"], lab_result, lab_test_status=lab_result["status"],
        )

    async def _ws_emit(self, event_type: str, payload: dict[str, Any]) -> None:
        """Fire-and-forget WS broadcast. Failures captured to Sentry if available."""
        try:
            from core.state import ws_manager
            await ws_manager.broadcast({
                "event_type": event_type,
                "payload": payload,
            })
        except Exception as exc:  # noqa: BLE001 — broadcast must never block dispatch
            log.debug("ws emit %s failed: %s", event_type, exc)
            from core.sentry_via_gateway import capture_exception as _sentry_capture
            _sentry_capture(exc, requester="brain-f4")

    # ------------------------------------------------------------------
    # C2 — GitHub MCP PR helpers (D2 template + D3 branch + diff)
    # ------------------------------------------------------------------

    @staticmethod
    def _find_closest_skill_yaml(
        name: str, skills_dir: Optional[Path] = None,
    ) -> Optional[tuple[str, str]]:
        """D2 — locate closest existing skill YAML by name similarity.

        Returns (filename, yaml_text) or None when no match / dir absent.
        Read-only — never writes skills/.
        """
        target_dir = skills_dir or (Path(__file__).resolve().parent.parent / "skills")
        if not target_dir.exists() or not target_dir.is_dir():
            return None
        candidates: list[tuple[str, Path]] = []
        for path in target_dir.glob("*.yaml"):
            candidates.append((path.stem, path))
        if not candidates:
            return None
        stems = [c[0] for c in candidates]
        matches = difflib.get_close_matches(name.lower(), [s.lower() for s in stems], n=1, cutoff=0.4)
        if not matches:
            # Substring fallback (name-contains heuristic).
            lname = (name or "").lower()
            for stem, path in candidates:
                if lname and (lname in stem.lower() or stem.lower() in lname):
                    try:
                        return path.name, path.read_text(encoding="utf-8")
                    except OSError:
                        return None
            return None
        matched_lower = matches[0]
        for stem, path in candidates:
            if stem.lower() == matched_lower:
                try:
                    return path.name, path.read_text(encoding="utf-8")
                except OSError:
                    return None
        return None

    @staticmethod
    def _generate_yaml_diff(
        proposal_yaml: str,
        existing: Optional[tuple[str, str]],
    ) -> str:
        """D2 — unified diff vs closest existing skill, fallback message if none."""
        if existing is None:
            return "# no diff available — first skill of this kind"
        fname, existing_text = existing
        diff = difflib.unified_diff(
            existing_text.splitlines(keepends=True),
            (proposal_yaml or "").splitlines(keepends=True),
            fromfile=f"skills/{fname}",
            tofile="proposal.yaml",
            n=3,
        )
        out = "".join(diff)
        if not out:
            return "# no changes vs closest existing skill"
        if len(out) > _YAML_DIFF_TRUNCATE:
            return out[:_YAML_DIFF_TRUNCATE] + "\n# ...[TRUNCATED]"
        return out

    @classmethod
    def _build_pr_body(
        cls,
        proposal: dict[str, Any],
        lab_result: dict[str, Any],
        yaml_diff: str,
    ) -> str:
        """D2 — render PR_BODY_TEMPLATE with proposal + lab data."""
        rationale = (
            proposal.get("description")
            or "(no rationale captured — owner_manual proposal)"
        )
        stdout = (lab_result.get("stdout") or "")[:_LAB_STREAM_TRUNCATE]
        stderr = (lab_result.get("stderr") or "")[:_LAB_STREAM_TRUNCATE]
        return PR_BODY_TEMPLATE.format(
            name=proposal.get("name", "unnamed"),
            source_pattern=proposal.get("source_pattern", "unknown"),
            proposal_id=proposal.get("id", "?"),
            yaml_diff=yaml_diff,
            lab_test_status=lab_result.get("status", "?"),
            latency_ms=lab_result.get("latency_ms", 0),
            exit_code=lab_result.get("exit_code", "?"),
            stdout_truncated=stdout,
            stderr_truncated=stderr,
            synthesis_rationale=str(rationale)[:1500],
        )

    # ------------------------------------------------------------------
    # C2 — dispatch_github_pr (D2 + D3 + D4 + D5)
    # ------------------------------------------------------------------

    async def dispatch_github_pr(self, proposal_id: str) -> dict[str, Any]:
        """C2 — fetch lab_passed proposal → mcp.github.create_pull_request.

        D4 BLOCK if lab_test_status != 'passed'.
        D5 GitHub MCP errors fail-fast (Sentry + WS emit).
        D2 PR body auto-template; D3 branch slug+shortid.
        D7 requester='brain-f4' threaded via dispatcher.invoke_tool kwarg.

        Returns:
            {status: "ok"|"blocked"|"failed", ...}
        Raises:
            LookupError on missing proposal (api layer → 404).
            RuntimeError on GitHub MCP failure (fail-fast surface for caller).
        """
        proposal = self.manager.get(proposal_id)  # raises LookupError

        # D4 — gate on lab result.
        lab_blob = json.loads(proposal.get("lab_test_result") or "{}")
        lab_status = lab_blob.get("status")
        if lab_status != "passed":
            log.warning(
                "PR creation BLOCKED — lab status=%s proposal_id=%s requester=%s",
                lab_status, proposal_id, F4_REQUESTER,
            )
            await self._ws_emit("brain.skill_pr_blocked", {
                "proposal_id": proposal_id,
                "reason": "lab_not_passed",
                "lab_status": lab_status,
            })
            return {
                "status": "blocked",
                "reason": "lab_not_passed",
                "proposal_id": proposal_id,
                "lab_test_status": lab_status,
            }

        # D3 — branch naming.
        name = proposal.get("name") or "unnamed"
        slug = _slugify(name)
        shortid = _shortid(proposal_id)
        branch_name = f"skill/proposal-{slug}-{shortid}"

        # D2 — diff + body.
        existing = self._find_closest_skill_yaml(name)
        yaml_diff = self._generate_yaml_diff(proposal.get("yaml_blob") or "", existing)
        body = self._build_pr_body(proposal, lab_blob, yaml_diff)

        owner = os.getenv("HERMES_GITHUB_OWNER", _DEFAULT_GITHUB_OWNER)
        repo = os.getenv("HERMES_GITHUB_REPO", _DEFAULT_GITHUB_REPO)
        base = os.getenv("HERMES_GITHUB_BASE_BRANCH", _DEFAULT_GITHUB_BASE)
        args = {
            "owner": owner,
            "repo": repo,
            "title": f"Skill proposal: {name}",
            "head": branch_name,
            "base": base,
            "body": body,
        }

        # D5 — fail-fast on GitHub MCP error (no retry).
        try:
            result = await self.dispatcher.invoke_tool(
                server="github",
                tool="create_pull_request",
                args=args,
                requester=F4_REQUESTER,
                caller_chapter="F.4",
            )
        except Exception as exc:  # noqa: BLE001 — defensive boundary; re-raised below.
            await self._handle_pr_failure(proposal_id, branch_name, exc)
            raise

        if not result.get("ok"):
            err = result.get("error") or "github_mcp_unknown_error"
            status_code = result.get("status_code")
            await self._handle_pr_failure(
                proposal_id, branch_name,
                RuntimeError(f"github MCP error: {err} (status_code={status_code})"),
            )
            return {
                "status": "failed",
                "proposal_id": proposal_id,
                "error": err,
                "status_code": status_code,
            }

        response = result.get("response") or {}
        pr_url = (
            response.get("html_url")
            or response.get("url")
            or response.get("pr_url")
        )
        pr_number = response.get("number") or response.get("pr_number")

        self.manager.update_pr_status(
            proposal_id,
            pr_url=pr_url,
            pr_branch=branch_name,
            pr_status="open",
        )

        await self._ws_emit("brain.skill_pr_created", {
            "proposal_id": proposal_id,
            "pr_url": pr_url,
            "pr_number": pr_number,
            "branch": branch_name,
        })

        log.info(
            "PR created proposal_id=%s pr_url=%s branch=%s requester=%s",
            proposal_id, pr_url, branch_name, F4_REQUESTER,
        )
        return {
            "status": "ok",
            "proposal_id": proposal_id,
            "pr_url": pr_url,
            "pr_number": pr_number,
            "branch": branch_name,
        }

    # ------------------------------------------------------------------
    # C3 — trigger_workflow_synthesis (PIVOT D6 honest scaffold)
    # ------------------------------------------------------------------

    async def trigger_workflow_synthesis(
        self,
        manual: bool = True,
        trigger_source: str = "api_manual",
    ) -> dict[str, Any]:
        """C3 PIVOT D6 — honest scaffold: persist synthesis_runs row + WS emit.

        Does NOT invoke Workflow tool. Workflow MCP is unavailable (Workflow is
        a Claude Code SDK harness feature, NOT a public MCP server) AND owner
        constraint subscription-only (zero paid API).

        Path forward:
          - F.4.3 UI manual button consumes 'queued' rows.
          - F.4.6 NOVA wires PATH 2 subprocess `claude --headless` consumer.

        Returns:
            {status: 'queued', run_id, trigger_type, message, scaffold_notice}
        """
        run_id = str(uuid.uuid4())
        now = datetime.now(timezone.utc).isoformat()

        conn = _sp_connect()
        try:
            ensure_synthesis_runs_table(conn)
            conn.execute(
                """INSERT INTO synthesis_runs
                   (id, trigger_type, status, queued_at, requester, trigger_source)
                   VALUES (?, ?, ?, ?, ?, ?)""",
                (
                    run_id,
                    "manual" if manual else "cron",
                    "queued",
                    now,
                    F4_REQUESTER,
                    trigger_source,
                ),
            )
            conn.commit()
        finally:
            conn.close()

        await self._ws_emit("brain.skill_synthesis_queued", {
            "run_id": run_id,
            "trigger_type": "manual" if manual else "cron",
            "queued_at": now,
            "trigger_source": trigger_source,
            "next_action": "F.4.3 UI manual button OR F.4.6 auto trigger",
        })

        log.info(
            "synthesis queued (scaffold honest D6) run_id=%s requester=%s source=%s",
            run_id, F4_REQUESTER, trigger_source,
        )

        return {
            "status": "queued",
            "run_id": run_id,
            "trigger_type": "manual" if manual else "cron",
            "queued_at": now,
            "trigger_source": trigger_source,
            "message": "Workflow execution scheduled. F.4.3 UI button OR F.4.6 auto.",
            "scaffold_notice": (
                "PIVOT D6 honest scaffold — Workflow MCP unavailable. "
                "F.4.6 NOVA delivers PATH 2 subscription subprocess."
            ),
        }

    async def _handle_pr_failure(
        self, proposal_id: str, branch_name: str, exc: BaseException,
    ) -> None:
        """D5 — persist pr_create_failed + Sentry + WS emit."""
        try:
            self.manager.update_pr_status(
                proposal_id,
                pr_url=None,
                pr_branch=branch_name,
                pr_status="not_created",
            )
        except Exception as persist_exc:  # noqa: BLE001 — never block failure surface
            log.warning("pr_create_failed persist exception: %s", persist_exc)
        from core.sentry_via_gateway import capture_exception as _sentry_capture
        _sentry_capture(exc, requester="brain-f4")
        await self._ws_emit("brain.skill_pr_create_failed", {
            "proposal_id": proposal_id,
            "branch": branch_name,
            "error": str(exc)[:200],
        })
        log.warning(
            "PR create failed proposal_id=%s requester=%s error=%s",
            proposal_id, F4_REQUESTER, str(exc)[:200],
        )
